# Generated by Django 5.2.5 on 2026-02-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobcard_status_jobstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='job_card_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
