# Generated by Django 5.2.5 on 2026-02-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobcard_job_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Corrective', 'Corrective'), ('Preventive', 'Preventive'), ('Breakdown', 'Breakdown')], max_length=20, null=True),
        ),
    ]
