# Generated by Django 5.2.5 on 2026-02-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobcard_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatuslog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobstatuslog',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
